# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nativeapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for nativeapp
  pod 'AppCenter/Analytics', '~> 1.5.0'
  pod 'AppCenterReactNativeShared', '~> 1.4.0'
  pod 'AppCenter/Crashes', '~> 1.5.0'

  

  platform :ios, '9.0'
  target 'nativeappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'nativeapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for nativeapp-tvOS

  target 'nativeapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
